export type LeadRow = {
  id: string;
  name: string;
  email: string;
  phone: string;
  message: string;
  status: 'new' | 'contacted' | 'qualified' | 'converted' | 'archived';
  created_at: string;
};
export type ClientRow = {
  id: string;
  name: string;
  email: string;
  phone: string;
  notes: string;
  origin?: string;
  created_from_lead?: string | null;
  created_at: string;
  lash_mapping?: string | null;
  lash_curl?: string | null;
  lash_thickness?: string | null;
  lash_length?: string | null;
  lash_adhesive?: string | null;
  lash_notes?: string | null;
};
export type ServiceRow = {
  id: string;
  slug: string;
  name: string;
  category: string;
  description: string;
  price_label: string;
  duration_label: string;
  duration_minutes: number;
  maintenance: string;
  intensity: number;
  sort_order: number;
  active: boolean;
};
export type GalleryRow = {
  id: string;
  title: string;
  subtitle: string;
  image_path: string;
  before_image_path?: string | null;
  alt_text: string;
  object_position: string;
  zoom: number;
  sort_order: number;
  active: boolean;
  public_url?: string;
};
export type AppointmentRow = {
  id: string;
  client_id?: string | null;
  lead_id?: string | null;
  service_id?: string | null;
  client_name: string;
  client_phone: string;
  starts_at: string;
  ends_at: string;
  status: 'scheduled' | 'confirmed' | 'completed' | 'cancelled' | 'no_show';
  notes: string;
  origin?: string;
  is_blocked?: boolean;
  reminder_sent_at?: string | null;
  reminder_same_day_sent_at?: string | null;
  post_care_sent_at?: string | null;
};
export type ExpenseRow = {
  id: string;
  description: string;
  amount: number;
  category: string;
  date: string;
  notes?: string | null;
  created_at: string;
};
export type TestimonialRow = {
  id: string;
  client_name: string;
  client_role: string;
  content: string;
  rating: number;
  active: boolean;
  sort_order: number;
  created_at: string;
};

export type AnamnesisRow = {
  id: string;
  client_name: string;
  client_phone: string;
  has_allergies: boolean;
  allergies_detail?: string | null;
  pregnant: boolean;
  eye_surgery: boolean;
  thyroid_issues: boolean;
  signature: string;
  created_at: string;
};
